trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/SolarSense.sln'  # Certifique-se de que o caminho esteja correto
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'  # Usando a variável

- script: |
    echo "Listando arquivos no diretório de fontes..."
    dir "$(Build.SourcesDirectory)"
  displayName: 'Listar arquivos no diretório de fontes'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'  # Usando a variável
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- script: |
    echo "Listando arquivos no diretório de artefatos..."
    dir "$(Build.ArtifactStagingDirectory)"
  displayName: 'Listar arquivos no diretório de artefatos'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Enzo Lafer RM551111(8b3c71f1-34e5-4ca5-adde-1783ea3a7d68)'  # Verifique se a assinatura está correta
    appType: 'webApp'
    appName: 'SolarSense'
    deployToSlotOrASE: true
    resourceGroupName: 'GS_SOLARSENSE'
    slotName: 'production'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
