trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: |
    echo "Listando arquivos no reposit贸rio..."
    dir "$(Build.SourcesDirectory)"
  displayName: 'Listar arquivos no reposit贸rio'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- script: |
    echo "Listando arquivos no diret贸rio de artefatos..."
    dir "$(Build.ArtifactStagingDirectory)"
  displayName: 'Listar arquivos no diret贸rio de artefatos'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Enzo Lafer RM551111(8b3c71f1-34e5-4ca5-adde-1783ea3a7d68)'
    appType: 'webApp'
    appName: 'SolarSense'
    package: '$(Build.ArtifactStagingDirectory)\WebApp.zip'  # Corrigido caminho do arquivo zip
    deploymentMethod: 'auto'
